### ISSUE TITLE
Possaible conflict with More Vehicles, AVO, 81 Tiles

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-WatchIt#3]
> A Steam player "Allystrya" discovered that the "Watch It" mod causes a game crash when used together with AVO, 81 Tiles and More Vehicles. Without "Watch It", all these three mods work fine together.

**Comment by dymanoid** [comment]
The original comments are here [on Steam Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1764208250).

> I have been able to duplicate your crash using the mods you have listed:
> - AVO,
> - More Vehicles
> - 81 Tiles (Bloody Penguin version)
> - TM:PE Labs
> - Less Steam
> - Watch It
> - Loading Screen Mod
> 
> There are not enough characters for me to go through my testing process I used and wacky things I have tried for the last day and a half BUT! I have had some success with 100% creation of a new game and all three with your configuration for over an hour now (I lost count how many times I have restarted but it takes about 2 minutes for me to load this each time).
> 
> Would you be willing to use the same map, on a new game, Use the above mods only EXCEPT! Watch It.
> 
> Make sure you are completely unsubbed from it before entering CS and tell me if you are able to load. **It is only when I resub to Watch It on your config that it then immediately will start crashing again.**

**Comment by dymanoid** [comment]
And another comment:

> I unsubscribed from Watch it! Then tried to load new map...all three mods work fine: AVO, More Vehicles and 81 Tiles.

**Comment by Allystrya** [comment]
Hello, Aubergine, I had no idea this was here until I was going through someone's compatibility log :) 

I am not sure if this is appropriate for me to comment here but I wasn't sure how else to give you a bit more information. So it was here or a discussion thread that yelled your name as a title.  I figured this would be better and I am sure you can always delete it  :) I want to clarify the mods listed in the Mod Compatibility Checker aren't quite accurate.  

I helped the gentleman because I love puzzles. I use 81 Tiles, AVO, More Vehicles, and Watch It among almost 90 mods and they all worked fine.  The gentleman I helped didn't even have 10 mods and I had all of the ones he had but the mods obviously didn't get along. After the above interaction I continued testing and found the crashes only occurred when Watch It was combined with 81 Tiles and no other mods subbed.

However with more testing there are certain mods when combined with the two will stop the crashing process.  Most of the Watch It author's mods will but not all.  There were other mods as well worked not even related to these at all.  I on the average did 5 loads of each mod that worked and retested each of those again after I went through every mod I happen to have.  (I wanted to make sure I wasn't seeing things after that many loads.)

I don't remember exactly what I saw in the logs. I have been keeping over a 100 crash folders from that day in case either author wants them. 

I reported my findings to the Mod Thread, BP, and Keallu and moved along with life after my own curiosity was met.  If you want a full list of mods that stop the crashes I can reproduce them again as I did not keep the logs from the working ones to see the differences.

I know it is wordy but figured giving the process might give some insight.

Thank you for listening.

**Comment by keallu** [comment]
I doubt there is an issue between AVO, 81 Tiles and Watch It! The issue is properly only with More Vehicles since it changes limits which Watch It! do monitor. With the new EML mod that changes prop limits Watch It! seemingly also causes a crash in that circumstance. I plan to test and debug this when I have time. I will keep More Vehicles in minds too.
